---
baseURL: 'https://www.mugen-hiko.co.jp/'

languageCode: 'ja-jp'
hasCJKLanguage: true

enableRobotsTXT: true

enableGitInfo: true

taxonomies: []

params:
  contactUrl: 'https://form.run/@mugen-hiko-contact'
  corporate:
    name:
      ja: '合同会社無限飛行'
      en: 'Mugen Hiko G.K.'
    zip_code: '336-0932'
    address: '埼玉県さいたま市緑区中尾665-3'
    established_at: '2017-05-19'
